CREATE TABLE IF NOT EXISTS players (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    loginname TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    name TEXT NOT NULL,
    civ INTEGER NOT NULL,
    email TEXT,
    created_on DATETIME DEFAULT CURRENT_TIMESTAMP,
    validated BOOLEAN DEFAULT 0,
    validation_code TEXT,
    last_load DATETIME DEFAULT CURRENT_TIMESTAMP,
    is_admin BOOLEAN DEFAULT 0,
    alliance_id INTEGER,
    score INTEGER DEFAULT 0,
    turn INTEGER DEFAULT 0,
    turns_free INTEGER DEFAULT 100,
    last_turn DATETIME DEFAULT CURRENT_TIMESTAMP,
    killed_by INTEGER DEFAULT 0,
    killed_by_name TEXT,
    FOREIGN KEY (alliance_id) REFERENCES alliances(id)
);
