CREATE TABLE IF NOT EXISTS players (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    loginname TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    name TEXT NOT NULL,
    civ INTEGER NOT NULL,
    email TEXT,
    created_on DATETIME DEFAULT CURRENT_TIMESTAMP,
    validated BOOLEAN DEFAULT 0,
    validation_code TEXT,
    last_load DATETIME DEFAULT CURRENT_TIMESTAMP,
    is_admin BOOLEAN DEFAULT 0,
    alliance_id INTEGER,
    score INTEGER DEFAULT 0,
    turn INTEGER DEFAULT 0,
    turns_free INTEGER DEFAULT 100,
    last_turn DATETIME DEFAULT CURRENT_TIMESTAMP,
    killed_by INTEGER DEFAULT 0,
    killed_by_name TEXT,
    -- Resources
    gold INTEGER DEFAULT 1000,
    food INTEGER DEFAULT 500,
    wood INTEGER DEFAULT 300,
    iron INTEGER DEFAULT 200,
    tools INTEGER DEFAULT 100,
    wine INTEGER DEFAULT 0,
    people INTEGER DEFAULT 10,
    -- Buildings
    woodcutter INTEGER DEFAULT 0,
    hunter INTEGER DEFAULT 0,
    farmer INTEGER DEFAULT 0,
    house INTEGER DEFAULT 0,
    iron_mine INTEGER DEFAULT 0,
    gold_mine INTEGER DEFAULT 0,
    tool_maker INTEGER DEFAULT 0,
    weapon_smith INTEGER DEFAULT 0,
    fort INTEGER DEFAULT 0,
    tower INTEGER DEFAULT 0,
    town_center INTEGER DEFAULT 0,
    market INTEGER DEFAULT 0,
    warehouse INTEGER DEFAULT 0,
    stable INTEGER DEFAULT 0,
    winery INTEGER DEFAULT 0,
    wall INTEGER DEFAULT 0,
    -- Military
    swordsman INTEGER DEFAULT 0,
    archers INTEGER DEFAULT 0,
    horseman INTEGER DEFAULT 0,
    catapults INTEGER DEFAULT 0,
    macemen INTEGER DEFAULT 0,
    trained_peasants INTEGER DEFAULT 0,
    thieves INTEGER DEFAULT 0,
    -- Equipment
    swords INTEGER DEFAULT 0,
    bows INTEGER DEFAULT 0,
    horses INTEGER DEFAULT 0,
    maces INTEGER DEFAULT 0,
    -- Land
    f_land INTEGER DEFAULT 0,
    m_land INTEGER DEFAULT 0,
    p_land INTEGER DEFAULT 0
);