civilizations:
  - id: 1
    name: "Vikings"
    description: "Fierce warriors from the North, masters of naval warfare and raiding"
    bonuses:
      military: 1.1
      construction: 1.0
      research: 1.0

  - id: 2
    name: "Franks"
    description: "Powerful European kingdom known for its strong defensive capabilities"
    bonuses:
      military: 1.0
      construction: 1.1
      research: 1.0

  - id: 3
    name: "Japanese"
    description: "Island nation with highly disciplined warriors and efficient training"
    bonuses:
      military: 1.1
      construction: 1.0
      research: 1.0

  - id: 4
    name: "Byzantines"
    description: "Eastern Roman Empire, center of learning and advanced technology"
    bonuses:
      military: 1.0
      construction: 1.0
      research: 1.1

  - id: 5
    name: "Mongols"
    description: "Nomadic warriors with unmatched cavalry and mobility"
    bonuses:
      military: 1.1
      construction: 1.0
      research: 1.0

  - id: 6
    name: "Incas"
    description: "Advanced civilization with efficient resource management"
    bonuses:
      military: 1.0
      construction: 1.1
      research: 1.0

  - id: 7
    name: "Chinese"
    description: "Ancient civilization with advanced construction techniques"
    bonuses:
      military: 1.0
      construction: 1.1
      research: 1.0

  - id: 8
    name: "Barbarians"
    description: "Fierce tribes known for their raiding and combat prowess"
    bonuses:
      military: 1.1
      construction: 1.0
      research: 1.0 